### ISSUE TITLE
Help with running the code

### ISSUE THREAD

**Issue by krishamehta** [samyachour/EKG_Analysis#20]
Hi,
I was hoping if anyone can help me run the program. I have all the dependencies installed. But I am confused as to how to run it. 

Thank You.

**Comment by samyachour** [comment]
Hi Krisha,

Look in the wiki under ["Testing our model"](https://github.com/samyachour/EKG_Analysis/wiki/Adding-a-feature-or-Testing-our-model) or on lines [44-49 of the model.py file](https://github.com/samyachour/EKG_Analysis/blob/master/model.py#L44). Follow those instructions and you should see the results!

Please note this project was _closed_ before the statistics group was able to fully implement their machine learning library in R. So it just uses a simple [SVM](http://scikit-learn.org/stable/modules/svm.html) for testing, which is not ideal for this application.

Feel free to fork and continue working on it!

Thanks,
Samy

**Comment by samyachour** [comment]
Reopening in case of further questions
